name: Cart CICD - Dev Branch
run-name: Cart CICD - Dev Branch
on:
  push:
    branches:
      - 'RB-**'
jobs:
  ci:
    uses: raghudevopsb82/github-reusable-actions/.github/workflows/ci-dev-branch.yml@main
    with:
      component: user
      appType: nodejs
    secrets:
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}




